name: bt.h tests
on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
      - name: Build tests
        run: |
          make CC=${{ matrix.cc }}
          ./test
      - name: Tests under the sanitizers
        run: |
          make -B CC=${{ matrix.cc }} FLAGS="-Wall -Wextra -Werror -g -std=c99 -fsanitize=address,undefined -fno-sanitize-recover=all"
          ./test
